builds:
- env:
  - CGO_ENABLED=0
  goos:
    - darwin
    - linux
archive:
  replacements:
    darwin: Darwin
    linux: LinuxS
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'