builds:
- env:
  - CGO_ENABLED=0
  goos:
    - darwin
    - linux
  ldflags:
    - -s -w
    - -X 'github.com/olegsu/iris/pkg/util.BuildVersion={{.Version}}'
    - -X 'github.com/olegsu/iris/pkg/util.BuildDate={{.Date}}'
    - -X 'github.com/olegsu/iris/pkg/util.BuildCommit={{.ShortCommit}}'
    - -X 'github.com/olegsu/iris/pkg/util.BuildBy=goreleaser'
archive:
  replacements:
    darwin: Darwin
    linux: LinuxS
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
