version: '1.0'

stages:
- Integration
- Delivery


steps:

  Prepare:
    title: Update Helm package version
    image: alpine:3.8
    stage: Integration
    commands:
    - apk add --no-cache curl jq python py-pip
    - pip install yq
    - sh ${{CF_VOLUME_PATH}}/iris/hack/.codefresh/push-helm.sh
      # ^-- cfexports IRIS_VERSION from VERSION file

  Test:
    title: Run unit test
    image: golang:1.11
    stage: Integration
    commands:
    - make test

  PushingHelmChart:
    title: Push Helm package to repo
    stage: Delivery
    image: codefresh/cfstep-helm:2.9.0
    environment:
    - ACTION=push
    - CHART_REF=iris

  CreatingGitTag:
    title: Push tag to git
    image: codefresh/cli
    stage: Delivery
    commands:
    - git remote rm origin
    - git remote add origin https://olegsu:${{GITHUB_TOKEN}}@github.com/olegsu/iris.git
    - git tag v${{IRIS_VERSION}}
    - git push --tags
    fail_fast: false
    when:
      branch:
        only:
        - master

  Releasing:
    image: goreleaser/goreleaser
    stage: Delivery
    fail_fast: false
    commands:
    - go mod download
    - goreleaser release -f .goreleaser.yml --rm-dist
    when:
      branch:
        only:
        - master

  BuildBinaries:
    image: goreleaser/goreleaser
    stage: Delivery
    fail_fast: false
    commands:
    - go mod download
    - goreleaser release -f .goreleaser.dev.yml --rm-dist --skip-publish --skip-validate
    when:
      branch:
        ignore:
        - master

  BuildingDockerImage:
    title: Building Docker Image
    type: build
    stage: Integration
    image_name: olsynt/iris
    tag: '${{CF_BRANCH_TAG_NORMALIZED}}'
    dockerfile: Dockerfile

  PushingToDockerRegistryVersion:
    title: Pushing to Docker Registry
    type: push
    stage: Delivery
    candidate: '${{BuildingDockerImage}}'
    tags:
    - ${{CF_BRANCH_TAG_NORMALIZED}}
    - ${{IRIS_VERSION}}
    registry: dockerhub

  PushingToDockerRegistryLatest:
    title: Pushing to Docker Registry
    type: push
    stage: Delivery
    candidate: '${{BuildingDockerImage}}'
    tag: latest
    registry: dockerhub
    when:
      branch:
        only:
        - master
