// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import filter "github.com/olegsu/iris/pkg/filter"
import mock "github.com/stretchr/testify/mock"

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

// GetFilterByName provides a mock function with given fields: _a0
func (_m *Service) GetFilterByName(_a0 string) (filter.Filter, error) {
	ret := _m.Called(_a0)

	var r0 filter.Filter
	if rf, ok := ret.Get(0).(func(string) filter.Filter); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(filter.Filter)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
