name: ci

on:
  push:
    branches: [ '*' ]

jobs:
  ci:
    name: ci
    runs-on: "ubuntu-18.04"
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '^1.18'
    - run: make test